title: "Śrī Rāmarcana Paddhati"
description: "OCR, transliteration, and translation using a Sanskrit Translation Protocol."
markdown: kramdown

#For Github Pages remote theme:
remote_theme: pages-themes/cayman@v0.2.0

plugins:
  -jekyll-remote-theme
